apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kondense
spec:
  selector:
    matchLabels:
      app: test-kondense
  replicas: 1
  template:
    metadata:
      labels:
        app: test-kondense
    spec:
      serviceAccountName: kondense
      containers:
      - name: stress-ng
        image: polinux/stress-ng
        command: [ "sleep", "1d" ]
        resources:
          limits:
            cpu: 100m
            memory: 100M
      - name: kondense
        image: kondense/kondense:1.0.1
        resources:
          limits:
            cpu: 0.3
            memory: 50M
        # env:
        # - name: EXCLUDE
        #   value: "stress-ng"
        # - name: STRESS-NG_MEMORY_INTERVAL
        #   value: "10"
        # - name: STRESS-NG_MEMORY_MAX_DEC
        #   value: "0.03"
        # - name: KONDENSE_MEMORY_INTERVAL
        #   value: "1"
        # - name: KONDENSE_MEMORY_MAX_DEC
        #   value: "0.03"
