---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    name: cadvisor
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    name: cadvisor